// Code generated by rice embed-go; DO NOT EDIT.
package databases

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "202101312211_create_table_user.down.sql",
		FileModTime: time.Unix(1612077118, 0),

		Content: string("drop table if exists \"user\";\ndrop table if exists \"product\";\ndrop table if exists \"order_history\";"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "202101312211_create_table_user.up.sql",
		FileModTime: time.Unix(1612078326, 0),

		Content: string("-- Table Definition ----------------------------------------------\n\nCREATE TABLE \"user\" (\n  \"id\" SERIAL PRIMARY KEY NOT NULL,\n  \"name\" varchar(80) NOT NULL,\n  \"email\" varchar(80) NOT NULL,\n  \"password\" varchar NOT NULL,\n  \"token\" varchar null,\n  \"tokenExpiredAt\" timestamptz null,\n  \"created_at\" timestamptz NOT NULL DEFAULT (now()),\n  \"created_by\" varchar(20) DEFAULT 'admin',\n  \"updated_at\" timestamptz NOT NULL DEFAULT (now()),\n  \"updated_by\" varchar(20) DEFAULT 'admin',\n  \"deleted_at\" timestamptz NULL,\n  \"deleted_by\" varchar(20) NULL\n);\n\nCREATE TABLE \"product\" (\n  \"id\" SERIAL PRIMARY KEY NOT NULL,\n  \"name\" varchar(80) NOT NULL,\n  \"qty\" int NOT NULL,\n  \"price\" int NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT (now()),\n  \"created_by\" varchar(20) DEFAULT 'admin',\n  \"updated_at\" timestamptz NOT NULL DEFAULT (now()),\n  \"updated_by\" varchar(20) DEFAULT 'admin',\n  \"deleted_at\" timestamptz NULL,\n  \"deleted_by\" varchar(20) NULL\n);\n\nCREATE TABLE \"order_history\" (\n  \"id\" SERIAL PRIMARY KEY NOT NULL,\n  \"user_id\" int,\n  \"product_id\" int NOT NULL,\n  \"qty\" int NOT NULL,\n  \"price\" int NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT (now()),\n  \"created_by\" varchar(20) DEFAULT 'admin',\n  \"updated_at\" timestamptz NOT NULL DEFAULT (now()),\n  \"updated_by\" varchar(20) DEFAULT 'admin',\n  \"deleted_at\" timestamptz NULL,\n  \"deleted_by\" varchar(20) NULL\n);\n\nALTER TABLE \"order_history\" ADD FOREIGN KEY (\"user_id\") REFERENCES \"user\" (\"id\");"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1612074654, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "202101312211_create_table_user.down.sql"
			file3, // "202101312211_create_table_user.up.sql"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`./migrations`, &embedded.EmbeddedBox{
		Name: `./migrations`,
		Time: time.Unix(1612074654, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"202101312211_create_table_user.down.sql": file2,
			"202101312211_create_table_user.up.sql":   file3,
		},
	})
}
