// Code generated by rice embed-go; DO NOT EDIT.
package databases

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "201911022211_create_table_user.down.sql",
		FileModTime: time.Unix(1612073386, 0),

		Content: string("drop table \"user\";"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "201911022211_create_table_user.up.sql",
		FileModTime: time.Unix(1612073386, 0),

		Content: string("-- Table Definition ----------------------------------------------\n\ncreate table public.\"user\"\n(\n\t\"id\" serial not null,\n\t\"name\" varchar(100) not null,\n\t\"email\" varchar(100) not null,\n\t\"password\" varchar(255) not null,\n\t\"merchantToken\" varchar(255) null,\n\t\"tokenExpiredAt\" timestamptz null,\n\t\"createdAt\" timestamptz NOT NULL,\n\t\"updatedAt\" timestamptz NOT NULL,\n\t\"deletedAt\" timestamptz,\n\tconstraint user_pkey primary key (\"id\")\n);"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1612073916, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "201911022211_create_table_user.down.sql"
			file3, // "201911022211_create_table_user.up.sql"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`./migrations`, &embedded.EmbeddedBox{
		Name: `./migrations`,
		Time: time.Unix(1612073916, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"201911022211_create_table_user.down.sql": file2,
			"201911022211_create_table_user.up.sql":   file3,
		},
	})
}
